package com.likeit.web.controller.handler.command;

public enum CommandName {

    GO_TO_AUTHORIZATION,
    GO_TO_REGISTRATION,
    AUTHORIZATION,
    REGISTRATION,
    QUESTIONS,
    QUESTION,
    GO_TO_QUESTION_CREATION,
    QUESTION_CREATION,
    GO_TO_QUESTION_EDITING,
    QUESTION_EDITING,
    QUESTION_DELETING,
    ANSWER_CREATION,
    ANSWER_EDITING,
    ANSWER_RATING,
    PROFILE,
    GO_TO_PROFILE_EDITING,
    PROFILE_EDITING,
    LOGOUT,

}
